// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dict.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	libresp "github.com/pku-hit/libresp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DictType int32

const (
	DictType_Root  DictType = 0
	DictType_Group DictType = 1
	DictType_Node  DictType = 2
)

var DictType_name = map[int32]string{
	0: "Root",
	1: "Group",
	2: "Node",
}

var DictType_value = map[string]int32{
	"Root":  0,
	"Group": 1,
	"Node":  2,
}

func (x DictType) String() string {
	return proto.EnumName(DictType_name, int32(x))
}

func (DictType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{0}
}

type DictStatus int32

const (
	DictStatus_Normal  DictStatus = 0
	DictStatus_Deleted DictStatus = 1
)

var DictStatus_name = map[int32]string{
	0: "Normal",
	1: "Deleted",
}

var DictStatus_value = map[string]int32{
	"Normal":  0,
	"Deleted": 1,
}

func (x DictStatus) String() string {
	return proto.EnumName(DictStatus_name, int32(x))
}

func (DictStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{1}
}

type DictItem struct {
	DictUniqueId         string          `protobuf:"bytes,1,opt,name=dictUniqueId,proto3" json:"dictUniqueId,omitempty"`
	Code                 string          `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 DictType        `protobuf:"varint,4,opt,name=type,proto3,enum=proto.DictType" json:"type,omitempty"`
	Status               DictStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=proto.DictStatus" json:"status,omitempty"`
	Value                *_struct.Struct `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DictItem) Reset()         { *m = DictItem{} }
func (m *DictItem) String() string { return proto.CompactTextString(m) }
func (*DictItem) ProtoMessage()    {}
func (*DictItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{0}
}

func (m *DictItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictItem.Unmarshal(m, b)
}
func (m *DictItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictItem.Marshal(b, m, deterministic)
}
func (m *DictItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictItem.Merge(m, src)
}
func (m *DictItem) XXX_Size() int {
	return xxx_messageInfo_DictItem.Size(m)
}
func (m *DictItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DictItem.DiscardUnknown(m)
}

var xxx_messageInfo_DictItem proto.InternalMessageInfo

func (m *DictItem) GetDictUniqueId() string {
	if m != nil {
		return m.DictUniqueId
	}
	return ""
}

func (m *DictItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DictItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DictItem) GetType() DictType {
	if m != nil {
		return m.Type
	}
	return DictType_Root
}

func (m *DictItem) GetStatus() DictStatus {
	if m != nil {
		return m.Status
	}
	return DictStatus_Normal
}

func (m *DictItem) GetValue() *_struct.Struct {
	if m != nil {
		return m.Value
	}
	return nil
}

type AddDictRequest struct {
	ParentId             string         `protobuf:"bytes,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Type                 DictType       `protobuf:"varint,2,opt,name=type,proto3,enum=proto.DictType" json:"type,omitempty"`
	Code                 string         `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value                *_struct.Value `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddDictRequest) Reset()         { *m = AddDictRequest{} }
func (m *AddDictRequest) String() string { return proto.CompactTextString(m) }
func (*AddDictRequest) ProtoMessage()    {}
func (*AddDictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{1}
}

func (m *AddDictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDictRequest.Unmarshal(m, b)
}
func (m *AddDictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDictRequest.Marshal(b, m, deterministic)
}
func (m *AddDictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDictRequest.Merge(m, src)
}
func (m *AddDictRequest) XXX_Size() int {
	return xxx_messageInfo_AddDictRequest.Size(m)
}
func (m *AddDictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDictRequest proto.InternalMessageInfo

func (m *AddDictRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *AddDictRequest) GetType() DictType {
	if m != nil {
		return m.Type
	}
	return DictType_Root
}

func (m *AddDictRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddDictRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDictRequest) GetValue() *_struct.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.DictType", DictType_name, DictType_value)
	proto.RegisterEnum("proto.DictStatus", DictStatus_name, DictStatus_value)
	proto.RegisterType((*DictItem)(nil), "proto.DictItem")
	proto.RegisterType((*AddDictRequest)(nil), "proto.AddDictRequest")
}

func init() { proto.RegisterFile("proto/dict.proto", fileDescriptor_22c1e80adc3f1fcd) }

var fileDescriptor_22c1e80adc3f1fcd = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0xba, 0xa4, 0xcb, 0xee, 0xa6, 0x91, 0x59, 0x1a, 0x44, 0x61, 0x42, 0x55, 0x11, 0x52,
	0x37, 0xd1, 0x44, 0x2a, 0xe2, 0x09, 0x5e, 0x10, 0x9d, 0xaa, 0x49, 0x68, 0x0f, 0x19, 0xf0, 0x9e,
	0x26, 0x97, 0xd4, 0x22, 0x89, 0x3d, 0xc7, 0x06, 0xf5, 0x8b, 0xf8, 0x12, 0x3e, 0x81, 0xff, 0x41,
	0x76, 0xd2, 0xac, 0xdb, 0x4a, 0x79, 0xca, 0xcd, 0x3d, 0xe7, 0xdc, 0x7b, 0x8e, 0x6d, 0xf0, 0xb8,
	0x60, 0x92, 0x45, 0x19, 0x4d, 0x65, 0x68, 0x4a, 0xe2, 0x98, 0x4f, 0x30, 0xc9, 0xa9, 0x5c, 0xaa,
	0x45, 0x98, 0xb2, 0x32, 0xe2, 0xdf, 0xd5, 0x64, 0x49, 0x65, 0x54, 0xd0, 0x85, 0xc0, 0x9a, 0x47,
	0x65, 0x9d, 0x4f, 0x74, 0xc1, 0xaa, 0x1a, 0x1b, 0x55, 0xf0, 0x3c, 0x67, 0x2c, 0x2f, 0x30, 0x32,
	0x7f, 0x0b, 0xf5, 0x2d, 0xc2, 0x92, 0xcb, 0x55, 0x0b, 0xbe, 0x78, 0x08, 0xfe, 0x14, 0x09, 0xe7,
	0x28, 0xea, 0x16, 0x3f, 0x7b, 0x88, 0xd7, 0x52, 0xa8, 0xb5, 0xa1, 0xd1, 0x1f, 0x0b, 0xdc, 0x19,
	0x4d, 0xe5, 0x95, 0xc4, 0x92, 0x8c, 0xe0, 0x48, 0x7b, 0xfd, 0x52, 0xd1, 0x5b, 0x85, 0x57, 0x99,
	0x6f, 0x0d, 0xad, 0xf1, 0x41, 0x7c, 0xaf, 0x47, 0x08, 0xd8, 0x29, 0xcb, 0xd0, 0xef, 0x1b, 0xcc,
	0xd4, 0xba, 0x57, 0x25, 0x25, 0xfa, 0x7b, 0x4d, 0x4f, 0xd7, 0xe4, 0x25, 0xd8, 0x72, 0xc5, 0xd1,
	0xb7, 0x87, 0xd6, 0xf8, 0x78, 0xfa, 0xa4, 0x59, 0x17, 0xea, 0x55, 0x9f, 0x57, 0x1c, 0x63, 0x03,
	0x92, 0x73, 0x18, 0xd4, 0x32, 0x91, 0xaa, 0xf6, 0x1d, 0x43, 0x3b, 0xd9, 0xa0, 0xdd, 0x18, 0x20,
	0x6e, 0x09, 0x64, 0x02, 0xce, 0x8f, 0xa4, 0x50, 0xe8, 0x0f, 0x86, 0xd6, 0xf8, 0x70, 0xfa, 0x2c,
	0x6c, 0x62, 0x85, 0xeb, 0x58, 0xe1, 0x8d, 0x89, 0x15, 0x37, 0xac, 0xd1, 0x2f, 0x0b, 0x8e, 0x3f,
	0x64, 0x99, 0x1e, 0x14, 0xe3, 0xad, 0xc2, 0x5a, 0x92, 0x00, 0x5c, 0x9e, 0x08, 0xac, 0x64, 0x97,
	0xac, 0xfb, 0xef, 0xdc, 0xf6, 0x77, 0xb9, 0x5d, 0x47, 0xdf, 0xdb, 0x12, 0xdd, 0xde, 0x88, 0xfe,
	0x7a, 0x6d, 0xd5, 0x31, 0x56, 0x9f, 0x3e, 0xb2, 0xfa, 0x55, 0xa3, 0xad, 0xd3, 0x8b, 0xf3, 0xe6,
	0x02, 0xf4, 0x1e, 0xe2, 0x82, 0x1d, 0x33, 0x26, 0xbd, 0x1e, 0x39, 0x00, 0x67, 0x2e, 0x98, 0xe2,
	0x9e, 0xa5, 0x9b, 0xd7, 0x2c, 0x43, 0xaf, 0x7f, 0xf1, 0x0a, 0xe0, 0xee, 0x64, 0x08, 0xc0, 0xe0,
	0x9a, 0x89, 0x32, 0x29, 0xbc, 0x1e, 0x39, 0x84, 0xfd, 0x19, 0x16, 0x28, 0x31, 0xf3, 0xac, 0xe9,
	0xef, 0x3e, 0xd8, 0x9a, 0x47, 0xde, 0x81, 0xfb, 0x89, 0xd6, 0x52, 0x8f, 0x24, 0x8f, 0x5d, 0x5c,
	0xea, 0x47, 0x14, 0x9c, 0x86, 0xed, 0xc3, 0x0b, 0x0d, 0xb5, 0x7d, 0x78, 0xa3, 0x1e, 0xb9, 0x84,
	0x23, 0xdd, 0xf9, 0xb8, 0xa4, 0x45, 0x26, 0xb0, 0x22, 0x67, 0xdb, 0x4e, 0x9c, 0x56, 0xb9, 0x09,
	0xf3, 0xef, 0x31, 0x6f, 0x61, 0xbf, 0xbd, 0x07, 0x72, 0xda, 0x1e, 0xeb, 0xfd, 0x7b, 0x09, 0x4e,
	0x3a, 0xe9, 0x86, 0xec, 0xbd, 0x09, 0x64, 0x64, 0xbb, 0x17, 0x6f, 0x55, 0xcf, 0xc0, 0x9d, 0xa3,
	0x34, 0x84, 0xff, 0xc8, 0xfd, 0x4e, 0x3e, 0xc7, 0x0a, 0x05, 0x4d, 0xef, 0xa6, 0x2c, 0x06, 0x46,
	0xf1, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xcd, 0xc1, 0xaf, 0xc7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictClient is the client API for Dict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictClient interface {
	ListRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*libresp.ListResponse, error)
	ListChildren(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error)
	AddDict(ctx context.Context, in *AddDictRequest, opts ...grpc.CallOption) (*libresp.Response, error)
	DelDict(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.Response, error)
	GetValue(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.GenericResponse, error)
}

type dictClient struct {
	cc *grpc.ClientConn
}

func NewDictClient(cc *grpc.ClientConn) DictClient {
	return &dictClient{cc}
}

func (c *dictClient) ListRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*libresp.ListResponse, error) {
	out := new(libresp.ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/ListRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) ListChildren(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error) {
	out := new(libresp.ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/ListChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) AddDict(ctx context.Context, in *AddDictRequest, opts ...grpc.CallOption) (*libresp.Response, error) {
	out := new(libresp.Response)
	err := c.cc.Invoke(ctx, "/proto.Dict/AddDict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) DelDict(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.Response, error) {
	out := new(libresp.Response)
	err := c.cc.Invoke(ctx, "/proto.Dict/DelDict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) GetValue(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.GenericResponse, error) {
	out := new(libresp.GenericResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServer is the server API for Dict service.
type DictServer interface {
	ListRoot(context.Context, *empty.Empty) (*libresp.ListResponse, error)
	ListChildren(context.Context, *wrappers.StringValue) (*libresp.ListResponse, error)
	AddDict(context.Context, *AddDictRequest) (*libresp.Response, error)
	DelDict(context.Context, *wrappers.StringValue) (*libresp.Response, error)
	GetValue(context.Context, *wrappers.StringValue) (*libresp.GenericResponse, error)
}

// UnimplementedDictServer can be embedded to have forward compatible implementations.
type UnimplementedDictServer struct {
}

func (*UnimplementedDictServer) ListRoot(ctx context.Context, req *empty.Empty) (*libresp.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoot not implemented")
}
func (*UnimplementedDictServer) ListChildren(ctx context.Context, req *wrappers.StringValue) (*libresp.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChildren not implemented")
}
func (*UnimplementedDictServer) AddDict(ctx context.Context, req *AddDictRequest) (*libresp.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDict not implemented")
}
func (*UnimplementedDictServer) DelDict(ctx context.Context, req *wrappers.StringValue) (*libresp.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelDict not implemented")
}
func (*UnimplementedDictServer) GetValue(ctx context.Context, req *wrappers.StringValue) (*libresp.GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}

func RegisterDictServer(s *grpc.Server, srv DictServer) {
	s.RegisterService(&_Dict_serviceDesc, srv)
}

func _Dict_ListRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/ListRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListRoot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_ListChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/ListChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListChildren(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_AddDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).AddDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/AddDict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).AddDict(ctx, req.(*AddDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_DelDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).DelDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/DelDict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).DelDict(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).GetValue(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dict",
	HandlerType: (*DictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoot",
			Handler:    _Dict_ListRoot_Handler,
		},
		{
			MethodName: "ListChildren",
			Handler:    _Dict_ListChildren_Handler,
		},
		{
			MethodName: "AddDict",
			Handler:    _Dict_AddDict_Handler,
		},
		{
			MethodName: "DelDict",
			Handler:    _Dict_DelDict_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Dict_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dict.proto",
}
