// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dict.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	libresp "github.com/pku-hit/libresp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DictType int32

const (
	DictType_OmitType DictType = 0
	DictType_Root     DictType = 1
	DictType_Group    DictType = 2
	DictType_Node     DictType = 3
)

var DictType_name = map[int32]string{
	0: "OmitType",
	1: "Root",
	2: "Group",
	3: "Node",
}

var DictType_value = map[string]int32{
	"OmitType": 0,
	"Root":     1,
	"Group":    2,
	"Node":     3,
}

func (x DictType) String() string {
	return proto.EnumName(DictType_name, int32(x))
}

func (DictType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{0}
}

type DictStatus int32

const (
	DictStatus_OmitStatus DictStatus = 0
	DictStatus_Normal     DictStatus = 1
	DictStatus_Deleted    DictStatus = 2
)

var DictStatus_name = map[int32]string{
	0: "OmitStatus",
	1: "Normal",
	2: "Deleted",
}

var DictStatus_value = map[string]int32{
	"OmitStatus": 0,
	"Normal":     1,
	"Deleted":    2,
}

func (x DictStatus) String() string {
	return proto.EnumName(DictStatus_name, int32(x))
}

func (DictStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{1}
}

type DictItem struct {
	DictUniqueId         string     `protobuf:"bytes,1,opt,name=dictUniqueId,proto3" json:"dictUniqueId,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 DictType   `protobuf:"varint,4,opt,name=type,proto3,enum=proto.DictType" json:"type,omitempty"`
	Status               DictStatus `protobuf:"varint,5,opt,name=status,proto3,enum=proto.DictStatus" json:"status,omitempty"`
	Value                string     `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DictItem) Reset()         { *m = DictItem{} }
func (m *DictItem) String() string { return proto.CompactTextString(m) }
func (*DictItem) ProtoMessage()    {}
func (*DictItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{0}
}

func (m *DictItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictItem.Unmarshal(m, b)
}
func (m *DictItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictItem.Marshal(b, m, deterministic)
}
func (m *DictItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictItem.Merge(m, src)
}
func (m *DictItem) XXX_Size() int {
	return xxx_messageInfo_DictItem.Size(m)
}
func (m *DictItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DictItem.DiscardUnknown(m)
}

var xxx_messageInfo_DictItem proto.InternalMessageInfo

func (m *DictItem) GetDictUniqueId() string {
	if m != nil {
		return m.DictUniqueId
	}
	return ""
}

func (m *DictItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DictItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DictItem) GetType() DictType {
	if m != nil {
		return m.Type
	}
	return DictType_OmitType
}

func (m *DictItem) GetStatus() DictStatus {
	if m != nil {
		return m.Status
	}
	return DictStatus_OmitStatus
}

func (m *DictItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddDictRequest struct {
	ParentId             string         `protobuf:"bytes,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Type                 DictType       `protobuf:"varint,2,opt,name=type,proto3,enum=proto.DictType" json:"type,omitempty"`
	Code                 string         `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value                *_struct.Value `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddDictRequest) Reset()         { *m = AddDictRequest{} }
func (m *AddDictRequest) String() string { return proto.CompactTextString(m) }
func (*AddDictRequest) ProtoMessage()    {}
func (*AddDictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c1e80adc3f1fcd, []int{1}
}

func (m *AddDictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDictRequest.Unmarshal(m, b)
}
func (m *AddDictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDictRequest.Marshal(b, m, deterministic)
}
func (m *AddDictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDictRequest.Merge(m, src)
}
func (m *AddDictRequest) XXX_Size() int {
	return xxx_messageInfo_AddDictRequest.Size(m)
}
func (m *AddDictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDictRequest proto.InternalMessageInfo

func (m *AddDictRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *AddDictRequest) GetType() DictType {
	if m != nil {
		return m.Type
	}
	return DictType_OmitType
}

func (m *AddDictRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddDictRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDictRequest) GetValue() *_struct.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.DictType", DictType_name, DictType_value)
	proto.RegisterEnum("proto.DictStatus", DictStatus_name, DictStatus_value)
	proto.RegisterType((*DictItem)(nil), "proto.DictItem")
	proto.RegisterType((*AddDictRequest)(nil), "proto.AddDictRequest")
}

func init() { proto.RegisterFile("proto/dict.proto", fileDescriptor_22c1e80adc3f1fcd) }

var fileDescriptor_22c1e80adc3f1fcd = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x13, 0x27, 0x75, 0xa7, 0x51, 0x70, 0x57, 0x14, 0x59, 0xa1, 0x42, 0x55, 0xb8, 0x94,
	0x8a, 0xd8, 0x52, 0x50, 0xc5, 0x01, 0x2e, 0x88, 0x54, 0x51, 0x25, 0x54, 0x24, 0x17, 0xb8, 0x3b,
	0xf6, 0xe0, 0xac, 0xb0, 0xbd, 0xdb, 0xf5, 0x18, 0x94, 0x77, 0xe0, 0x3d, 0x78, 0x09, 0x1e, 0x0e,
	0xed, 0xda, 0x71, 0xd3, 0x1f, 0xb5, 0x12, 0xa7, 0x9d, 0x99, 0x6f, 0xbe, 0x99, 0x6f, 0x66, 0x07,
	0x5c, 0xa9, 0x04, 0x89, 0x20, 0xe1, 0x31, 0xf9, 0xc6, 0x64, 0x7d, 0xf3, 0x8c, 0xa7, 0x29, 0xa7,
	0x55, 0xb5, 0xf4, 0x63, 0x91, 0x07, 0xf2, 0x47, 0x35, 0x5d, 0x71, 0x0a, 0x32, 0xbe, 0x54, 0x58,
	0xca, 0x20, 0x2f, 0xd3, 0xa9, 0x36, 0x44, 0x51, 0x62, 0xcd, 0x1a, 0x3f, 0x4f, 0x85, 0x48, 0x33,
	0x0c, 0x8c, 0xb7, 0xac, 0xbe, 0x07, 0x98, 0x4b, 0x5a, 0x37, 0xe0, 0x8b, 0xdb, 0xe0, 0x2f, 0x15,
	0x49, 0x89, 0xaa, 0x6c, 0xf0, 0xc3, 0xdb, 0x78, 0x49, 0xaa, 0xda, 0x08, 0x9a, 0xfc, 0xb5, 0xc0,
	0x99, 0xf3, 0x98, 0xce, 0x09, 0x73, 0x36, 0x81, 0xa1, 0xd6, 0xfa, 0xb5, 0xe0, 0x57, 0x15, 0x9e,
	0x27, 0x9e, 0x75, 0x64, 0x1d, 0xef, 0x86, 0x37, 0x62, 0x8c, 0x81, 0x1d, 0x8b, 0x04, 0xbd, 0xae,
	0xc1, 0x8c, 0xad, 0x63, 0x45, 0x94, 0xa3, 0xd7, 0xab, 0x63, 0xda, 0x66, 0x2f, 0xc1, 0xa6, 0xb5,
	0x44, 0xcf, 0x3e, 0xb2, 0x8e, 0x47, 0xb3, 0x27, 0x75, 0x3b, 0x5f, 0xb7, 0xfa, 0xb2, 0x96, 0x18,
	0x1a, 0x90, 0xbd, 0x82, 0x41, 0x49, 0x11, 0x55, 0xa5, 0xd7, 0x37, 0x69, 0xfb, 0x5b, 0x69, 0x97,
	0x06, 0x08, 0x9b, 0x04, 0xf6, 0x14, 0xfa, 0x3f, 0xa3, 0xac, 0x42, 0x6f, 0x60, 0x9a, 0xd4, 0xce,
	0xe4, 0x8f, 0x05, 0xa3, 0x0f, 0x49, 0xa2, 0xf3, 0x43, 0xbc, 0xaa, 0xb0, 0x24, 0x36, 0x06, 0x47,
	0x46, 0x0a, 0x0b, 0x6a, 0x07, 0x68, 0xfd, 0x56, 0x54, 0xf7, 0x21, 0x51, 0x9b, 0x09, 0x7b, 0xf7,
	0x4c, 0x68, 0x6f, 0x4d, 0xf8, 0x7a, 0xa3, 0x48, 0x6b, 0xdf, 0x9b, 0x3d, 0xf3, 0xeb, 0x45, 0xfb,
	0x9b, 0x45, 0xfb, 0xdf, 0x34, 0xda, 0x28, 0x3d, 0x79, 0x5b, 0xef, 0x59, 0xf7, 0x61, 0x43, 0x70,
	0x3e, 0xe7, 0xdc, 0xd8, 0x6e, 0x87, 0x39, 0x60, 0x87, 0x42, 0x90, 0x6b, 0xb1, 0x5d, 0xe8, 0x2f,
	0x94, 0xa8, 0xa4, 0xdb, 0xd5, 0xc1, 0x0b, 0x91, 0xa0, 0xdb, 0x3b, 0x39, 0x05, 0xb8, 0x5e, 0x07,
	0x1b, 0x01, 0x68, 0x6a, 0xed, 0xb9, 0x1d, 0x06, 0x30, 0xb8, 0x10, 0x2a, 0x8f, 0x32, 0xd7, 0x62,
	0x7b, 0xb0, 0x33, 0xc7, 0x0c, 0x09, 0x13, 0xb7, 0x3b, 0xfb, 0xdd, 0x03, 0x5b, 0xf3, 0xd8, 0x3b,
	0x70, 0x3e, 0xf1, 0x92, 0x74, 0x0b, 0x76, 0x57, 0xe3, 0x99, 0xbe, 0xa4, 0xf1, 0x81, 0xdf, 0x5c,
	0x9f, 0x6f, 0x52, 0x9b, 0xeb, 0x9b, 0x74, 0xd8, 0x19, 0x0c, 0x75, 0xe4, 0x63, 0x44, 0x98, 0x0a,
	0xb5, 0x66, 0x87, 0x77, 0x0a, 0x5c, 0x92, 0xe2, 0x45, 0x6a, 0x46, 0x7d, 0xbc, 0xcc, 0x8a, 0x67,
	0x89, 0xc2, 0xe2, 0x7f, 0xcb, 0x9c, 0xc2, 0x4e, 0xf3, 0xd9, 0xec, 0xa0, 0xf9, 0xbb, 0x9b, 0x9f,
	0x3f, 0xde, 0x6f, 0xa9, 0x5b, 0xb4, 0xf7, 0x66, 0x2f, 0x86, 0xf6, 0x70, 0xe3, 0x7b, 0xd9, 0x73,
	0x70, 0x16, 0x48, 0x26, 0xe1, 0x11, 0xba, 0xd7, 0xd2, 0x17, 0x58, 0xa0, 0xe2, 0xf1, 0x75, 0x95,
	0xe5, 0xc0, 0x30, 0xde, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x60, 0xeb, 0x44, 0x13, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictClient is the client API for Dict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictClient interface {
	// 获取全部Root节点列表
	ListRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*libresp.ListResponse, error)
	// 获取某一分类下的Root节点列表
	ListCategory(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error)
	// 获取某一节点组下的子节点列表
	ListChildren(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error)
	// 添加字典
	AddDict(ctx context.Context, in *AddDictRequest, opts ...grpc.CallOption) (*libresp.Response, error)
	// 删除字典项
	DelDict(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.Response, error)
	// 通过字典ID获取指定节点的值
	GetValue(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.GenericResponse, error)
}

type dictClient struct {
	cc *grpc.ClientConn
}

func NewDictClient(cc *grpc.ClientConn) DictClient {
	return &dictClient{cc}
}

func (c *dictClient) ListRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*libresp.ListResponse, error) {
	out := new(libresp.ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/ListRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) ListCategory(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error) {
	out := new(libresp.ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/ListCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) ListChildren(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.ListResponse, error) {
	out := new(libresp.ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/ListChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) AddDict(ctx context.Context, in *AddDictRequest, opts ...grpc.CallOption) (*libresp.Response, error) {
	out := new(libresp.Response)
	err := c.cc.Invoke(ctx, "/proto.Dict/AddDict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) DelDict(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.Response, error) {
	out := new(libresp.Response)
	err := c.cc.Invoke(ctx, "/proto.Dict/DelDict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) GetValue(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*libresp.GenericResponse, error) {
	out := new(libresp.GenericResponse)
	err := c.cc.Invoke(ctx, "/proto.Dict/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServer is the server API for Dict service.
type DictServer interface {
	// 获取全部Root节点列表
	ListRoot(context.Context, *empty.Empty) (*libresp.ListResponse, error)
	// 获取某一分类下的Root节点列表
	ListCategory(context.Context, *wrappers.StringValue) (*libresp.ListResponse, error)
	// 获取某一节点组下的子节点列表
	ListChildren(context.Context, *wrappers.StringValue) (*libresp.ListResponse, error)
	// 添加字典
	AddDict(context.Context, *AddDictRequest) (*libresp.Response, error)
	// 删除字典项
	DelDict(context.Context, *wrappers.StringValue) (*libresp.Response, error)
	// 通过字典ID获取指定节点的值
	GetValue(context.Context, *wrappers.StringValue) (*libresp.GenericResponse, error)
}

// UnimplementedDictServer can be embedded to have forward compatible implementations.
type UnimplementedDictServer struct {
}

func (*UnimplementedDictServer) ListRoot(ctx context.Context, req *empty.Empty) (*libresp.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoot not implemented")
}
func (*UnimplementedDictServer) ListCategory(ctx context.Context, req *wrappers.StringValue) (*libresp.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategory not implemented")
}
func (*UnimplementedDictServer) ListChildren(ctx context.Context, req *wrappers.StringValue) (*libresp.ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChildren not implemented")
}
func (*UnimplementedDictServer) AddDict(ctx context.Context, req *AddDictRequest) (*libresp.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDict not implemented")
}
func (*UnimplementedDictServer) DelDict(ctx context.Context, req *wrappers.StringValue) (*libresp.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelDict not implemented")
}
func (*UnimplementedDictServer) GetValue(ctx context.Context, req *wrappers.StringValue) (*libresp.GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}

func RegisterDictServer(s *grpc.Server, srv DictServer) {
	s.RegisterService(&_Dict_serviceDesc, srv)
}

func _Dict_ListRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/ListRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListRoot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_ListCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/ListCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListCategory(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_ListChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/ListChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListChildren(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_AddDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).AddDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/AddDict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).AddDict(ctx, req.(*AddDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_DelDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).DelDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/DelDict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).DelDict(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dict/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).GetValue(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dict",
	HandlerType: (*DictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoot",
			Handler:    _Dict_ListRoot_Handler,
		},
		{
			MethodName: "ListCategory",
			Handler:    _Dict_ListCategory_Handler,
		},
		{
			MethodName: "ListChildren",
			Handler:    _Dict_ListChildren_Handler,
		},
		{
			MethodName: "AddDict",
			Handler:    _Dict_AddDict_Handler,
		},
		{
			MethodName: "DelDict",
			Handler:    _Dict_DelDict_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Dict_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dict.proto",
}
